version: '3.7'

x-loucast: &locust
    image: locust
    build:
      context: ./services/attacker-locust
      dockerfile: Dockerfile
    environment: &locust-env
      TARGET_HOST: "${TARGET_HOST:-http://localhost}"
      TEST_FILE: "${TEST_FILE:-tasks.py}"
    volumes:
    - ./services/attacker-locust/locust-tasks:/locust-tasks
    - ./:/work

services:
  attacker:
    build: 
      context: ./services/attacker
      dockerfile: Dockerfile
    volumes:
      - ./stress-test:/stress-test
    command: tail -f > /dev/null
  target:
    build: 
      context: ./services/target
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./services/target/app/app.js:/app/app.js
    ports:
      - 3000:3000
    command: node app.js
  master:
    <<: *locust
    environment:
      <<: *locust-env
      LOCUST_MODE: master
    ports:
      - 8089:8089
    working_dir: /work
    command: /locust-tasks/run.sh
  slave:
    <<: *locust
    environment:
      <<: *locust-env
      LOCUST_MODE: worker
      MASTER_HOST: master
    links:
      - master
    command: /locust-tasks/run.sh
