version: '3.7'
services:
  attacker:
    build: 
      context: ./services/attacker
      dockerfile: Dockerfile
    volumes:
      - ./stress-test:/stress-test
    command: tail -f > /dev/null
  target:
    build: 
      context: ./services/target
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./services/target/app/app.js:/app/app.js
    ports:
      - 3000:3000
    command: node app.js
